from youtube_transcript_api import YouTubeTranscriptApi

GROVER_videoID = "PYhvoxLw8N4"
ROHAN_videoID = "HfKXabrKUQ8"

transcriptList = YouTubeTranscriptApi.list_transcripts(GROVER_videoID)
# for transcript in transcriptList:
#   print(
#         transcript.video_id,
#         transcript.language,
#         transcript.language_code,
#         # whether it has been manually created or generated by YouTube
#         transcript.is_generated,
#         # whether this transcript can be translated or not
#         transcript.is_translatable,
#         # a list of languages the transcript can be translated to
#         transcript.translation_languages,
#     )

# transcript = YouTubeTranscriptApi.get_transcript(GROVER_videoID, 'hi')
translatedTranscript = None
for transcript in transcriptList:
  if transcript.language_code == 'hi':
    # print(transcript)
    translatedTranscript = transcript.translate('en').fetch()
    # print(translatedTranscript)

if translatedTranscript:
    with open('transcript.txt', 'a') as file:
        for entry in translatedTranscript:
            file.write(entry['text'] + " ")
else:
    print("Hindi transcript not found or could not be translated.")